export const envDefinitions = [
  { key: 'NODE_ENV' },
  { key: 'PORT', type: 'int', log: true },
  { key: 'JWT_SECRET', minLength: 32 },
  { key: 'JWT_REFRESH_SECRET', minLength: 32 },
  { key: 'DB_USER' },
  { key: 'DB_PASSWORD' },
  { key: 'DB_NAME' },
  { key: 'DB_HOST' },
  { key: 'DB_PORT', type: 'int' },
  { key: 'DB_FORCE_SYNC', type: 'bool', log: true },
  { key: 'SSL_KEY_PATH' },
  { key: 'SSL_CERT_PATH' },
  { key: 'USE_SSL', type: 'bool' },
  { key: 'SMTP_HOST' },
  { key: 'FROM_EMAIL' },
  { key: 'SMTP_USER' },
  { key: 'SMTP_PASS' },
  { key: 'SMTP_PORT' },
  { key: 'ADMIN_USER_NAME' },
  { key: 'ADMIN_PASSWORD' },
  { key: 'ADMIN_PLAYER_NAME' },
  { key: 'GAME_INACTIVE_INTERVAL', type: 'int', log: true },
  { key: 'GAME_INACTIVE_TIMEOUT', type: 'int', log: true },
  { key: 'MULTIPLE_GAMES_PER_HOST', type: 'bool', log: true },
];
